{% set name = "pynhd" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 19c8ac08c689c489d37cbfe68fdc84dbfd36a8283b818b1bb02c4c454c5bd02c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16.0,>=0.15.2
    - cytoolz
    - geopandas-base >=0.10
    - fiona
    - networkx
    - numpy >=1.21
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc <0.16.0,>=0.15.2
    - pygeoutils <0.16.0,>=0.15.2
    - shapely >=1.8.5

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
