{% set name = "pynhd" %}
{% set version = "0.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 9fc00673ac6fd06eb668a5c16e0f6cd7910caa9b7b2bdd57a149f6440288ad30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async_retriever >=0.3.5
    - shapely >=1.8
    - pygeoutils >=0.13.5
    - geopandas >=0.8
    - pygeoogc >=0.13.5
    - networkx
    - pyarrow >=1.0.1
    - pandas >=1.0
    - numpy >=1.17
    - cytoolz

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
