{% set name = "pynhd" %}
{% set version = "0.13.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: a459fe1348c196db64e1256e7e4dfcd0fa2b3e49305561a9e501a19814d25c7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.8
    - cytoolz
    - geopandas >=0.9
    - loguru
    - networkx
    - numpy >=1.17
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc >=0.13.8
    - pygeoutils >=0.13.10
    - shapely >=1.8

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
