{% set name = "pynhd" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e533fc049c6c8574634129d9ca4dc11af83baa8716e7a43d8f6b8b5a1b07b534

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools
    - pygeoutils
    - pygeoogc
    - networkx

test:
  imports:
    - pynhd

about:
  home: https://github.com/cheginit/pynhd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Process and access NHD+ V2 data through NLDI and WaterData web services.

  description: |
    PyNHD is a part of Hydrodata software stack that provides access to NHDPlus
    data though NLDI and WaterData web services.
  doc_url: https://hydrodata.readthedocs.io
  dev_url: https://github.com/cheginit/pynhd

extra:
  recipe-maintainers:
    - cheginit
