{% set name = "pynhd" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 0abd8b26a9b336ed4167ddc89577bd26251563d33620cb0ea87dcb4447abc0ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - brotlipy
    - chardet
    - cytoolz
    - defusedxml
    - geopandas
    - nest-asyncio
    - netcdf4
    - networkx
    - orjson
    - owslib
    - pyarrow
    - pygeoogc
    - pygeoutils
    - pyproj
    - python >=3.6
    - rasterio
    - requests
    - setuptools
    - shapely
    - simplejson
    - xarray

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pynhd
  summary: Process and access NHDPlus V2 data through NLDI and WaterData web services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
