{% set name = "pynhd" %}
{% set version = "0.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 5fa5d179caa27c0ec94bc41c3d110fb1321c7d4e753bb43f83651410ff9fe792

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.2.4
    - cytoolz
    - geopandas >=0.7
    - networkx
    - numpy >=1.17
    - pandas >=1.0
    - pyarrow
    - pygeoogc >=0.11.5
    - pygeoutils >=0.11.4
    - python >=3.7
    - requests
    - shapely >=1.6
    - simplejson

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pynhd
  summary: Process and access NHDPlus V2 data through NLDI and WaterData web services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
