{% set name = "pynhd" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: c0bd34f5b92804cebb1dbea9a2cad951eae90668840cd3884be5a1e72dcea756

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.12
    - cytoolz
    - geopandas >=0.10
    - networkx
    - numpy >=1.21
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc >=0.13.12
    - pygeoutils >=0.13.12
    - shapely >=1.8

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
