{% set name = "pynhd" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 6e8ca1d2184f83657f1ccaa13fc3c1ba3fb59c6e3a2e3da0389b8e288ea9825c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16.0,>=0.15.0
    - cytoolz
    - geopandas >=0.10
    - networkx
    - numpy >=1.21
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc <0.16.0,>=0.15.0
    - pygeoutils <0.16.0,>=0.15.0
    - shapely >=1.8.5

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
