{% set name = "pynhd" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: fb51695e3826b52c93cfe99193449d5a992a3e53312341b86d54f92a8ed88cca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3.2
    - cytoolz
    - geopandas >=0.7
    - networkx
    - numpy >=1.17
    - pandas >=1.0
    - pyarrow
    - pygeoogc >=0.13
    - pygeoutils >=0.13
    - python >=3.7
    - shapely >=1.6
    - importlib_metadata

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pynhd
  summary: Navigate and subset the National Hydrography Dataset Plus using web services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
