{% set name = "pynhd" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: d600339419651755ca5be5478d7a4998b185a239c0d4ef8051c1c223d02fdf60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - async-retriever <0.18,>=0.17
    - cytoolz
    - geopandas-base >=0.10
    - pyogrio
    - networkx
    - numpy >=1.21
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc <0.18,>=0.17
    - pygeoutils <0.18,>=0.17
    - shapely >=2

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
