{% set name = "pynhd" %}
{% set version = "0.13.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 3d71287556223b367e624c8e1cc7811be28ab48b990f63185e23f834a16e153b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - async_retriever >=0.3.4
    - cytoolz
    - geopandas >=0.8
    - networkx
    - numpy >=1.17
    - pandas >=1.0
    - pyarrow
    - pygeoogc >=0.13.3
    - pygeoutils >=0.13.2
    - python >=3.8
    - shapely >=1.7

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pynhd
  summary: Navigate and subset the National Hydrography Dataset Plus using web services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
