{% set name = "pynhd" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 540c21a315e89c59b8635917522ea5ba30180742d4aacee2e35f601ba61e7ad1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - cytoolz
    - geopandas
    - networkx
    - numpy
    - pandas
    - pyarrow
    - pygeoogc
    - pygeoutils
    - python >=3.7
    - requests
    - shapely
    - simplejson

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pynhd
  summary: Process and access NHDPlus V2 data through NLDI and WaterData web services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
