{% set name = "pynhd" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: dcf789cd9c9dcc241b0b8ab27f007dda894bdaf31cdd062d7cc1d347570a0a8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3
    - cytoolz
    - geopandas >=0.7
    - networkx
    - numpy >=1.17
    - pandas >=1.0
    - pyarrow
    - pygeoogc >=0.12
    - pygeoutils >=0.12
    - python >=3.7
    - requests
    - shapely >=1.6
    - importlib_metadata

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pynhd
  summary: Process and access NHDPlus V2 data through NLDI and WaterData web services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
