{% set name = "pynhd" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: b18e29cd4e3ad240b209639436809cd40e75cc6812751ee9f09390bbb36c4a66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.17,>=0.16
    - cytoolz
    - geopandas-base >=0.10
    - fiona
    - networkx
    - numpy >=1.21
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc <0.17,>=0.16
    - pygeoutils <0.17,>=0.16
    - shapely >=2

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
